### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Felipe-UnB** [pvermees/IsoplotRgui#1]
Mr. Vermeesch, for which R version IsoplotRgui is available? I was trying to install it on my computer and I received the warning below.

![image](https://user-images.githubusercontent.com/8608912/28148989-a073a7a2-6760-11e7-9c34-1ab980e11ef1.png)

**Comment by pvermees** [comment]
IsoplotRgui is not on CRAN. You'll have to install it from GitHub with devtools. To do so, please enter the following commands at the R prompt:

```
install.packages('devtools')`
install.packages('shiny')
library(devtools)
install_github('pvermees/IsoplotR')
install_github('pvermees/IsoplotRgui')
```
Once installed, IsoplotRgui can be run as follows:
```
library(IsoplotRgui)
IsoplotR()
```
Further details can be found in the README file and at http://isoplotr.london-geochron.com

**Comment by Felipe-UnB** [comment]
Thanks! Package installed and running.
