### ISSUE TITLE
IsoplotRgui uses Port 3838, same port as the shiny-server

### ISSUE THREAD

**Issue by angmos** [pvermees/IsoplotRgui#142]
I want to have IsoplotRgui and shiny-server on the same server and I have realized IsoplotRgui  uses the port  3838, that is already in use by the shiny-server. I have managed to change the port to  3839 for IsoplotRgui but I guess it could be also inidcated on the notes for its build.

**Comment by pvermees** [comment]
Yes you can assign a different port to IsoplotRgui by replacing `daemon(3838)` with `daemon(3839)`, say. I will change the documentation accordingly. Thanks for the feedback.
