### ISSUE TITLE
Need introduction on seting up IsoplotRgui server

### ISSUE THREAD

**Issue by cycleuser** [pvermees/IsoplotRgui#33]
I try to git clone this repo and use the `IsoplotRgui/inst/shiny-examples/myapp/www` folder on my server, which does run the GUI but has no plot function:

[http://labof.me:3838/sample-apps/www/ ](http://labof.me:3838/sample-apps/www/ )

The shiny server on my server seems to work well, but there seems non instructions on how to set up a server of IsoplotRgui.

I have put this whole repo at [http://labof.me:3838/IsoplotRgui/](http://labof.me:3838/IsoplotRgui/) and also installed both rstudio and shiny-server, but can still not make it work.

A instruction on how to organize **the server files** for IsoplotRgui is needed.
It will be awesome if you show what exatly you put in your **shiny-server** folder.

How about include the server folder of everything under the path at **[http://pieter-vermeesch.es.ucl.ac.uk/shiny/IsoplotRshiny/](http://pieter-vermeesch.es.ucl.ac.uk/shiny/IsoplotRshiny/)`** to this repo?

Then all need to build a server is to clone the **same folder you are using on your server** into others' shiny-server www path.

**Comment by cycleuser** [comment]
the problems seem caused by the `server.R` not working.

The whole web will get a `No UI defined` error with the `server.R` file at the R folder, as a neighbour of the `www` folder.

Then the web works but plot of corse faild with the `server.R` renamed as 
[http://labof.me:3838/sample-apps/badserver.R](http://labof.me:3838/sample-apps/badserver.R)

The combination of IsoplotR and IsoplotRgui and the building process of that `server.R` seem responsible for these problems.

It might be a good idea to build a seperately repo of `IsoplotRshiny`, and let the `IsoplotRshiny` can be git cloned and hold on a shiny-server with no need to suffer from the failings.

**Comment by cycleuser** [comment]
Which version of R are you using on your server? I am using the default 3.4.4 provided by Ubuntu apt source. 

I am now trying to update R to 3.5, which totally destroy every packages including devtools.
It might take a lot time to try to install the broken chains one by one, and hope it works finally.

Maybe it is a better choice to build a docker containing all it need to run IsoplotRshiny?

**Comment by pvermees** [comment]
The problem lies with shiny, which was updated from version 1.2.0 to 1.3.0 on April 7, breaking IsoplotRgui. Revert to the old version to avoid the problem:

```
library(devtools)
install_version("shiny", version = "1.2.0", repos = "http://cran.r-project.org")
```

A bug report has been filed to shiny. Hopefully they will fix the problem soon.

**Comment by cycleuser** [comment]
Awesome man , I am writing a manul on building the server.
