### ISSUE TITLE
Renumbering after omit

### ISSUE THREAD

**Issue by zimshady** [pvermees/IsoplotRgui#55]
In the online shiny app, when data is fully omitted (i.e. with capital X), all rows below the omitted row are dynamically renumbered. Is it possible to make the numbering static? This is the case with U-Pb concordia. I have not tested this in other cases.

**Comment by pvermees** [comment]
I'm not sure if I understand the problem. When I omit the first 8 rows in the U-Pb dataset, IsoplotR labels the remaining points as 9 and 10. Is this not what you want? Ar-Ar data behave identically. I haven't tried the other data types.

**Comment by zimshady** [comment]
This is exactly what I want and I have retried today and all seems to be behaving normally. Apologies for wasting your time!
